steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/cozbrand/back/$_ENV:$COMMIT_SHA'
      - '.'
images:
  - 'asia-east1-docker.pkg.dev/cozbrand/back/$_ENV:$COMMIT_SHA'
options:
  machineType: 'E2_HIGHCPU_8'