// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: merchant.sql

package model

import (
	"context"
)

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, code, host, encrypt_salt, is_enabled, created_at, updated_at
FROM merchant
WHERE id = ?
`

func (q *Queries) GetMerchant(ctx context.Context, id uint64) (Merchant, error) {
	row := q.queryRow(ctx, q.getMerchantStmt, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Host,
		&i.EncryptSalt,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantByHost = `-- name: GetMerchantByHost :one
SELECT id, name, code, host, encrypt_salt, is_enabled, created_at, updated_at
FROM merchant
WHERE host = ?
`

func (q *Queries) GetMerchantByHost(ctx context.Context, host string) (Merchant, error) {
	row := q.queryRow(ctx, q.getMerchantByHostStmt, getMerchantByHost, host)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Host,
		&i.EncryptSalt,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
