// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package model

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdminLogin(ctx context.Context, arg AdminLoginParams) (Admin, error)
	CheckEmailExist(ctx context.Context, arg CheckEmailExistParams) (int32, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) error
	CreateMember(ctx context.Context, arg CreateMemberParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (sql.Result, error)
	CreateProductSpec(ctx context.Context, arg CreateProductSpecParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteProductCategory(ctx context.Context, arg DeleteProductCategoryParams) error
	DeleteProductSecondLevelSpec(ctx context.Context, arg DeleteProductSecondLevelSpecParams) error
	DeleteProductSpec(ctx context.Context, arg DeleteProductSpecParams) error
	DeleteProductSpecByProductID(ctx context.Context, arg DeleteProductSpecByProductIDParams) error
	DeleteProductStock(ctx context.Context, arg DeleteProductStockParams) error
	DeleteProductStockByProductID(ctx context.Context, arg DeleteProductStockByProductIDParams) error
	GetMemberInfo(ctx context.Context, id uint64) (GetMemberInfoRow, error)
	GetMerchant(ctx context.Context, id uint64) (Merchant, error)
	GetMerchantByHost(ctx context.Context, host string) (Merchant, error)
	GetProduct(ctx context.Context, arg GetProductParams) (GetProductRow, error)
	GetProductCategory(ctx context.Context, arg GetProductCategoryParams) (ProductCategory, error)
	GetProductCategoryChildrenIDs(ctx context.Context, arg GetProductCategoryChildrenIDsParams) ([]uint64, error)
	GetProductCategoryTopCount(ctx context.Context, merchantID uint64) (int64, error)
	GetProductCountByCategoryID(ctx context.Context, arg GetProductCountByCategoryIDParams) (int64, error)
	GetProductSpec(ctx context.Context, arg GetProductSpecParams) ([]GetProductSpecRow, error)
	GetProductSpecByID(ctx context.Context, arg GetProductSpecByIDParams) (ProductSpec, error)
	GetProductSpecTitlesByProductID(ctx context.Context, arg GetProductSpecTitlesByProductIDParams) ([]string, error)
	GetProductStock(ctx context.Context, arg GetProductStockParams) ([]GetProductStockRow, error)
	ListProductSecondLevelSpecIDs(ctx context.Context, arg ListProductSecondLevelSpecIDsParams) ([]uint64, error)
	MemberLogin(ctx context.Context, arg MemberLoginParams) (Member, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	SwitchProductStatus(ctx context.Context, arg SwitchProductStatusParams) error
	UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) error
	UpdateProductCategoryLeftTree(ctx context.Context, arg UpdateProductCategoryLeftTreeParams) error
	UpdateProductCategoryRightTree(ctx context.Context, arg UpdateProductCategoryRightTreeParams) error
	UpdateProductCategoryTopID(ctx context.Context, arg UpdateProductCategoryTopIDParams) error
	UpdateProductSales(ctx context.Context, arg UpdateProductSalesParams) error
	UpdateProductSpec(ctx context.Context, arg UpdateProductSpecParams) error
	UpdateProductStockQuantity(ctx context.Context, arg UpdateProductStockQuantityParams) error
}

var _ Querier = (*Queries)(nil)
