// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/identity/merchant/domain/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "ecommerce-api/pkg/identity/merchant/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMerchantRepository is a mock of MerchantRepository interface.
type MockMerchantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryMockRecorder
}

// MockMerchantRepositoryMockRecorder is the mock recorder for MockMerchantRepository.
type MockMerchantRepositoryMockRecorder struct {
	mock *MockMerchantRepository
}

// NewMockMerchantRepository creates a new mock instance.
func NewMockMerchantRepository(ctrl *gomock.Controller) *MockMerchantRepository {
	mock := &MockMerchantRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepository) EXPECT() *MockMerchantRepositoryMockRecorder {
	return m.recorder
}

// GetMerchantByHost mocks base method.
func (m *MockMerchantRepository) GetMerchantByHost(ctx context.Context, host string) (entity.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByHost", ctx, host)
	ret0, _ := ret[0].(entity.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByHost indicates an expected call of GetMerchantByHost.
func (mr *MockMerchantRepositoryMockRecorder) GetMerchantByHost(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByHost", reflect.TypeOf((*MockMerchantRepository)(nil).GetMerchantByHost), ctx, host)
}
